/********************************************************************************************
* @name                 WaiverEmailHandlerTest
* @description          Code coverage for WaiverEmailHandler class.
* @date                 12/01/2026
* @cretaedby            Maksud
*********************************************************************************************
* version               Author              Date            Comments
* 1.0                   Maksud           12/01/2026     Initial Version
*********************************************************************************************
*/

@isTest
public class WaiverEmailHandlerTest {

}